GET http://127.0.0.1:8000/api/books/
#Authorization: Bearer {{ access }}
###
POST http://127.0.0.1:8000/api/books/
Content-Type: application/json

{
    "title": "War and war",
    "description": "A novel",
    "price": "30.00",
    "created_at": "2026-01-10",
    "author_id": 3,
    "category_ids": [4]}
###
GET http://127.0.0.1:8000/api/books/5/
###
PUT http://127.0.0.1:8000/api/books/7/
Content-Type: application/json

{
    "title": "Dune",
    "description": "Science fiction novel",
    "price": "30.00",
    "created_at": "2026-01-10",
    "author_id": 1,
    "category_ids": [3, 5]
}
###
PATCH http://127.0.0.1:8000/api/books/5/
Content-Type: application/json

{

    "price": "35.00"

}
###
DELETE http://127.0.0.1:8000/api/books/7/
###
GET http://127.0.0.1:8000/api/books/?category=2&author=3
###
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
    "username": "misko",
    "password": "123"
}
