GET http://127.0.0.1:8000/api/books/?ordering=-price
#Authorization: Bearer {{ access }}
###
POST http://127.0.0.1:8000/api/books/
Authorization: Bearer {{access}}
Content-Type: application/json

{
    "title": "Narnia",
    "description": "popular book",
    "price": "37.00",
    "created_at": "2025-09-16",
    "author_id": 1,
    "category_ids": [3]}
###
GET http://127.0.0.1:8000/api/books/5/
###
PUT http://127.0.0.1:8000/api/books/7/
Content-Type: application/json

{
    "title": "Dune",
    "description": "Science fiction novel",
    "price": "30.00",
    "created_at": "2026-01-10",
    "author_id": 1,
    "category_ids": [3, 5]
}
###
PATCH http://127.0.0.1:8000/api/books/11/
Authorization: Bearer {{access}}
Content-Type: application/json

{

    "price": "66.00"

}
###
DELETE http://127.0.0.1:8000/api/books/6/
Authorization: Bearer {{access}}
###
GET http://127.0.0.1:8000/api/books/?category=2&author=3
###
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
    "username": "milomir",
    "password": "123"
}
###

